---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen

platforms:
  - name: ubuntu-16.04
  - name: debian-9

verifier:
  name: serverspec

suites:
  - name: default
    verifier:
      patterns:
        - roles/ansible-dotfiles/test/integration/default/serverspec/default_spec.rb
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
